In [2]:
square_dict = {num:num*num for num in range(1, 11)}
square_dict

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [4]:
old_price = {'milk' : 1.02, 'coffee':2.5, 'bread':2.5}
dollar_to_pound = 0.76

In [5]:
new_price = {item :value*dollar_to_pound for (item, value) in old_price.items()}
new_price

{'milk': 0.7752, 'coffee': 1.9, 'bread': 1.9}

In [6]:
original_dict = {'jack': 38, 'michael': 48, 'guido': 57, 'john': 33}

In [ ]:
even_dict = {k:v for (k, v) in original_dict.items() if }

In [1]:
from bs4 import BeautifulSoup
import pandas as pd 
import requests

In [3]:
url = "https://www/olx.com.pk/cars_c84?page=1"
resp = requests.get(url)

In [10]:
import pandas as pd 
from jupyter_datatables import init_datatables_mode

In [11]:
# pip install jupyter-datatables

In [12]:
%load_ext jupyter_require

%requirejs d3 https://d3js.org/d3.v5.min

init_datatables_mode()

The jupyter_require extension is already loaded. To reload it, use:
  %reload_ext jupyter_require

In [14]:
df = pd.read_csv("uber_data.csv")

In [16]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,3/1/2016 0:00,3/1/2016 0:07,1,2.50,-73.976746,40.765152,1,N,-74.004265,40.746128,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,1,3/1/2016 0:00,3/1/2016 0:11,1,2.90,-73.983482,40.767925,1,N,-74.005943,40.733166,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,2,3/1/2016 0:00,3/1/2016 0:31,2,19.98,-73.782021,40.644810,1,N,-73.974541,40.675770,1,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,2,3/1/2016 0:00,3/1/2016 0:00,3,10.78,-73.863419,40.769814,1,N,-73.969650,40.757767,1,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,2,3/1/2016 0:00,3/1/2016 0:00,5,30.43,-73.971741,40.792183,3,N,-74.177170,40.695053,1,98.0,0.0,0.0,0.00,15.50,0.3,113.80

In [1]:
thislist = ["apple", "banana", "cherry"]

In [2]:
thislist[1]

'banana'

In [3]:
thislist[1] = "Mango"

In [4]:
thislist

['apple', 'Mango', 'cherry']

In [5]:
# print the last item in list 
thislist[-1]

'cherry'

In [219]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]

In [8]:
thislist[2:5]

['cherry', 'orange', 'kiwi']

In [9]:
len(thislist)

7

In [10]:
thislist.pop()

'mango'

In [11]:
len(thislist)

6

In [13]:
thislist[4:]

['kiwi', 'melon']

In [17]:
thislist[-4:]

['cherry', 'orange', 'kiwi', 'melon']

In [25]:
target_text = "apple"
[item for item in thislist if item.lower() == target_text.lower()]

['apple']

In [20]:
my_list = ['apple', 'banana', 'orange', 'kiwi']
target_text = 'Apple'

# Perform case-insensitive text check using list comprehension
matches = [item for item in my_list if item.lower() == target_text.lower()]

print(matches)  # Output: ['apple']

['apple']

In [214]:
[item for item in thislist if item == target_text]

['apple']

In [29]:
[item for item in thislist if item.lower() == target_text.lower()]

['apple']

In [31]:
bits = [False, True,False, True,False, True,True,False, True]

In [216]:
[0 if b==False else 1 for b in bits]

[0, 1, 0, 1, 0, 1, 1, 0, 1]

In [218]:
thislist

['apple',
 'banana',
 'cherry',
 [5, 2, 8, 1, 9],
 [5, 2, 8, 1, 9],
 5,
 2,
 8,
 1,
 9,
 5,
 2,
 8,
 1,
 9]

In [220]:
[item.upper() for item in thislist]

['APPLE', 'BANANA', 'CHERRY', 'ORANGE', 'KIWI', 'MELON', 'MANGO']

In [44]:
my_string = "HelloMyNameIsHamza"

In [50]:
"".join([i if i.islower() else " " + i for i in my_string])[1:]

'Hello My Name Is Hamza'

In [53]:
# square number for first 10 digits 
[num**2 for num in range(0,11)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [54]:
{num:num for num in range(0, 11)}

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10}

In [55]:
my_string

'HelloMyNameIsHamza'

In [56]:
# to print in reverse order
my_string[::-1]

'azmaHsIemaNyMolleH'

In [57]:
thislist[::-1]

['melon', 'kiwi', 'orange', 'cherry', 'banana', 'apple']

In [58]:
numbers = [1, 2, 3, 4, 5]

In [60]:
# find modulas of 2
[num for num in numbers if num%2==0 ]

[2, 4]

In [61]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

for x in fruits:
  if "a" in x:
    newlist.append(x)

print(newlist)

['apple', 'banana', 'mango']

In [64]:
[x for x in fruits if "a" in x]

['apple', 'banana', 'mango']

In [66]:
thislist.pop(3)

'orange'

In [67]:
thislist

['apple', 'banana', 'cherry', 'kiwi', 'melon']

In [68]:
[x for x in fruits if x!="apple"]

['banana', 'cherry', 'kiwi', 'mango']

In [72]:
# sort list 
thislist.sort()

In [73]:
my_list = [5, 2, 8, 1, 9]
sorted_list = sorted(my_list, reverse=True)

In [74]:
sorted_list

[9, 8, 5, 2, 1]

In [75]:
sorted(my_list, reverse=False)

[1, 2, 5, 8, 9]

In [82]:
new_list = thislist, my_list
newlist

['apple', 'banana', 'mango']

In [83]:
my_list

[5, 2, 8, 1, 9]

In [87]:
thislist.extend(my_list)

In [101]:
def fib(n):
    a= 0 
    b =1
    if n==0:
        print(a)
    elif n==1:
        print(a)
        print(b)
    else:
        print(a)
        print(b)
        for i in range(2, n+1):
            a, b = b, a+b
            print(b)
            
fib(1)

0
1

In [103]:
def factorial(n):
    if n < 0:
        return "Factorial is not defined for negative numbers."
    elif n == 0 or n == 1:
        return 1
    else:
        result = 1
        for i in range(2, n+1):
            result *= i
        return result

In [104]:
factorial(5)

120

In [130]:
def fib(n):
    a, b = 0, 1
    if n==0:
        print(a)
    elif n==1:
        print(a, b)
    else:
        print(a)
        print(b)
        for i in range(2, n+1):
            a, b = b, a+b
            print(b)
            
fib(10)

0
1
1
2
3
5
8
13
21
34
55

In [134]:
def fib(n):
    try:
        a, b = 0, 1
        if n==0 or n<0:
            print('Enter Value greater than 0')
        
        elif n==1:
            print(a, b)
            
        else:
            print(a)
            print(b)
            for i in range(2, n+1):
                a, b = b, a+b
                print(b)
                
    except Exception as e:
        return str(e)
    
fib(1)

(0, 1)

In [108]:
def sum_of(a, b):
    return a+b

sum_of(2,5)

7

In [110]:
def fun(a, b):
    num1 = a 
    num2 = b 
    result = num1+num2
    return "The sum of these param is  ", result

fun(2,4 )

('The sum of these param is  ', 6)

In [112]:
# """"lambda is an anonymous function in which we can have multiple arguments but can only have only one expression""""

In [113]:
x = lambda a : a + 10
print(x(5))

15

In [115]:
x = lambda a:a+10
print(x(5))

x = lambda a, b : a * b
print(x(5, 6))

15

In [116]:
x = lambda a, b : a*b
print(x(5, 6))

30

In [120]:
x = lambda a, b, c : (a + b) * c
print("The result is :" ,x(5, 6, 7))

('The result is :', 77)

In [124]:
x = lambda a, b, c : a+b+c
print(x(5, 6, 7))

18

In [128]:
def fun(a, b ):
    num1 = a 
    num2 = b
    result = num1+num2
    return "The sum is ", result
fun(1,5)

('The sum is ', '6')

In [135]:
import json

# some JSON:
x =  '{ "name":"John", "age":30, "city":"New York"}'

# parse x:
y = json.loads(x)

# the result is a Python dictionary:
print(y["age"])

30

In [144]:
import json

# some JSON:
x =  '{ "name":"John", "age":30, "city":"New York"}'

# parse x:
y = json.loads(x)

# the result is a Python dictionary:
print(y["age"])

30

In [155]:
file = {
  "name": "John Doe",
  "age": 30,
  "email": "johndoe@example.com",
  "address": {
    "street": "123 Main St",
    "city": "New York",
    "state": "NY",
    "zipcode": "10001"
  },
  "phoneNumbers": [
    {
      "type": "home",
      "number": "555-1234"
    },
    {
      "type": "work",
      "number": "555-5678"
    }
  ],
  "isEmployed": True,
  "languages": ["English", "Spanish", "French"],
  "skills": {
    "programming": ["Python", "JavaScript", "Java"],
    "database": ["MySQL", "MongoDB"],
    "frameworks": ["Flask", "Django", "React"]
  }
}

# y = json.loads(file)
print(file['age'])

30

In [189]:
for key, value in file.items():
    req_json = {}
    ph_numbers = []

    for ph in file['phoneNumbers']:
        number = ph['number']
        ph_numbers.append(number)

    languages = file['languages']
    frame_work =file['skills']['frameworks']
    
    
    req_json.append(ph_numbers)
    req_json.append(languages)
    req_json.append(frame_work)
    
print(req_json)

AttributeError: 'dict' object has no attribute 'append'

In [199]:
file['skills']['frameworks']

['Flask', 'Django', 'React']

In [200]:
req_data = []

phone_numbers = []
phone_number = file['phoneNumbers']
for ph in phone_number:
    number = ph['number']
    phone_numbers.append(number)
    
languages = file['languages']
framework = file['skills']['frameworks']

req_data.append(phone_numbers)
req_data.append(languages)
req_data.append(frame_work)
print(req_data)

[['555-1234', '555-5678'], ['English', 'Spanish', 'French'], ['Flask', 'Django', 'React']]

In [179]:
ph_numbers = []

for ph in file['phoneNumbers']:
    number = ph['number']
    phone_numbers.append(number)
    
print(phone_numbers)

['555-5678', '555-1234', '555-5678']

In [180]:
for lang in file['languages']:
    print(lang)

English
Spanish
French

In [181]:
file['skills']['database']

['MySQL', 'MongoDB']

In [170]:
languages = []

programming = file['skills']['programming']
print(programming[0])

Python

In [164]:
programming_languages = file["skills"]["programming"]
for language in programming_languages:
    print(language)

Python
JavaScript
Java

In [163]:
for lang in file['languages']:
    program = lang['programming']
    print(program[0])

TypeError: string indices must be integers, not str

In [ ]:
phone_numbers = []

# Iterate over the phone numbers
for phone_number in file['phoneNumbers']:
    number = phone_number['number']
    phone_numbers.append(number)

print(phone_numbers)

In [150]:
import json

# Open the JSON file
with open('sample.json') as file:
    # Load the JSON data
    data = json.load(file)

# Access the data from the JSON
print(data)

In [213]:
import requests

url = 'https://w3schools.com/python/demopage.html'
resp = requests.get(url)
resp.status_code
# resp.text

404

In [ ]:
import requests

url = 'https://www.w3schools.com/python/demopage.php'
myobj = {'somekey': 'somevalue'}

x = requests.post(url, json = myobj)

print(x.text)

In [209]:
import requests

url = 'https://www.w3schools.com/python/demopage.php'
my_obj = {
    'Name' : 'Hamza',
    'Age' : 25,
    'Discipline' : 'BCS(Hons)'
         }

x = requests.post(url, json=my_obj)
print(x.text)

In [ ]:
url = 'https://www.w3schools.com/python/demopage.php'
my_obj = {
    'Name' : 'Hamza', 
    'Age' : 26, 
    'Discipline' : 'BCS(Hons)'
}

x = requests.post(url, json=my_obj)
 print(x.text)

In [210]:
import requests

# Send a DELETE request
response = requests.delete('https://example.com/api/endpoint')

# Get the status code
status_code = response.status_code

# Print the status code
print(status_code)

404

In [211]:
url  = "https://w3schools.com/python/demopage.php"

response = requests.delete(url)
status_code = response.status_code
print(status_code)

200

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data_sets/orders.csv')

In [3]:
df.head()

  Order ID  Order Date CustomerName           State     City
0  B-26055  10-03-2018    Harivansh   Uttar Pradesh  Mathura
1  B-25993  03-02-2018       Madhav           Delhi    Delhi
2  B-25973  24-01-2018  Madan Mohan   Uttar Pradesh  Mathura
3  B-25923  27-12-2018        Gopal     Maharashtra   Mumbai
4  B-25757  21-08-2018     Vishakha  Madhya Pradesh   Indore

In [7]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

In [12]:
df.to_csv('Orders.csv', index=False)

In [15]:
df[
    df['Order Date'].isnull()
]

Empty DataFrame
Columns: [Order ID, Order Date, CustomerName, State, City]
Index: []

In [16]:
df['Order Date'].dtype

dtype('<M8[ns]')

In [9]:
df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce')

In [12]:
df['Order Date'].dtype

dtype('O')

In [11]:
df['Order Date'] = df['Order Date'].dt.strftime('%Y-%m-%d')

In [13]:
df.to_csv('test_file.csv', index=False)

In [14]:
df.head()

  Order ID  Order Date CustomerName           State     City
0  B-26055  2018-10-03    Harivansh   Uttar Pradesh  Mathura
1  B-25993  2018-03-02       Madhav           Delhi    Delhi
2  B-25973  2018-01-24  Madan Mohan   Uttar Pradesh  Mathura
3  B-25923  2018-12-27        Gopal     Maharashtra   Mumbai
4  B-25757  2018-08-21     Vishakha  Madhya Pradesh   Indore

In [15]:
df.head()

  Order ID  Order Date CustomerName           State     City
0  B-26055  2018-10-03    Harivansh   Uttar Pradesh  Mathura
1  B-25993  2018-03-02       Madhav           Delhi    Delhi
2  B-25973  2018-01-24  Madan Mohan   Uttar Pradesh  Mathura
3  B-25923  2018-12-27        Gopal     Maharashtra   Mumbai
4  B-25757  2018-08-21     Vishakha  Madhya Pradesh   Indore